require 'Scenes/Scene'

require 'Scenes/MainMenuScene'
require 'Scenes/TitleScene'
require 'Scenes/TestScene1'
require 'Scenes/TestScene2'
require 'Scenes/TestScene3'
require 'Scenes/FontTestScene'
require 'Scenes/IntroductionScene'
require 'Scenes/TestScene4'
require 'Scenes/VarTutShirtScene'
require 'Scenes/VarTutBackpackScene'
require 'Scenes/VarTutFriendScene'
require 'Scenes/VarMinigameIntro'
require 'Scenes/VarMinigameBackpack'
require 'Scenes/MultiVarMusicIntro'
require 'Scenes/MultiVarMelodyMaker'
require 'Scenes/CTS'
