require 'Commands/Command'

require 'Commands/SetValTo'
require 'Commands/SetNoteTo'
require 'Commands/SetValTo2'
require 'Commands/AppleMoveLeft'
require 'Commands/AppleMoveRight'
require 'Commands/End'
require 'Commands/Condition'
require 'Commands/Else'
require 'Commands/Condition2'
require 'Commands/SetChordTo'
